<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="CommunityToolkit.WinUI.Controls.SettingsControls" Version="8.2.251219" />
    <PackageVersion Include="CommunityToolkit.WinUI.Converters" Version="8.2.251219" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2705" />
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="2.4.0" />
    <PackageVersion Include="Microsoft.WindowsAppSDK.AI" Version="2.4.4" />
    <PackageVersion Include="Microsoft.WindowsAppSDK.ML" Version="2.1.74" />
    <PackageVersion Include="Microsoft.WindowsAppSDK.WinUI" Version="2.3.6" />
    <PackageVersion Include="Microsoft.WindowsAppSDK.DWrite" Version="2.1.0" />
    <PackageVersion Include="Microsoft.WindowsAppSDK.Runtime" Version="2.4.0" />
    <PackageVersion Include="Microsoft.WindowsAppSDK.Widgets" Version="2.0.5" />
    <PackageVersion Include="Microsoft.Windows.AI.MachineLearning" Version="2.1.74" />
    <PackageVersion Include="Microsoft.Xaml.Behaviors.WinUI.Managed" Version="3.0.1" />
    <PackageVersion Include="ReswPlus" Version="0.5.0" />
    <PackageVersion Include="WinUIEx" Version="2.9.3" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageVersion Include="MemoryPack" Version="1.21.4" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tasks" Version="10.0.12" />
    <PackageVersion Include="ZLinq" Version="1.5.6" />
    <PackageVersion Include="ZLogger" Version="2.5.10" />
    <PackageVersion Include="TUnit" Version="1.66.27" />
  </ItemGroup>
</Project>