<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
        <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
        <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
        <IsAotCompatible>True</IsAotCompatible>
        <InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.EntityFrameworkCore.GeneratedInterceptors</InterceptorsNamespaces>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm"/>
        <PackageReference Include="FFmpegInteropX"/>
        <PackageReference Include="MemoryPack"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tasks">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="ZLinq"/>
        <PackageReference Include="ZLogger"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Messages\"/>
        <Folder Include="Factories\"/>
    </ItemGroup>
</Project>
